builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

archives:
  - name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: git-get
    description: Go gets your code
    homepage: https://github.com/arbourd/git-get

    test: |
      repo = "github.com/arbourd/git-get"
      assert_match "#{testpath}/src/#{repo}", shell_output("#{bin}/git-get #{repo}")

      cd "#{testpath}/src/#{repo}" do
        assert_match "https://#{repo}", shell_output("git remote -v")
      end

    conflicts:
      - git-extras

    folder: Formula

    repository:
      owner: arbourd
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    commit_author:
      name: Dylan Arbour
      email: arbourd@users.noreply.github.com
